/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-03-12 00:11:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import quiz.Quiz;
import quiz.Question;
import quiz.MAQuestion;
import java.util.*;
import java.util.Date;
import user.*;
import java.util.*;
import java.sql.*;
import org.json.simple.parser.JSONParser;
import org.json.simple.JSONObject;
import quiz.JSONCreator;
import quiz.ScoreBoard;
import quiz.ScoreBoard.Score;
import org.json.simple.parser.ParseException;

public final class HistorySummaryPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("user");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("quiz.JSONCreator");
    _jspx_imports_classes.add("quiz.Question");
    _jspx_imports_classes.add("org.json.simple.JSONObject");
    _jspx_imports_classes.add("org.json.simple.parser.ParseException");
    _jspx_imports_classes.add("quiz.Quiz");
    _jspx_imports_classes.add("org.json.simple.parser.JSONParser");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("quiz.ScoreBoard");
    _jspx_imports_classes.add("quiz.ScoreBoard.Score");
    _jspx_imports_classes.add("quiz.MAQuestion");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

ServletContext context = getServletContext(); 
DBConnection connect = (DBConnection)(context.getAttribute("Connection"));

String currentuser = (String)session.getAttribute("user");

Statement stmt = connect.getStatement();

ScoreBoard board = null; 




      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("\t<title>");
      out.print(currentuser );
      out.write("'s Quiz History </title>\n");
      out.write("\t<link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\">\n");
      out.write("\t<link rel=\"stylesheet\" href=\"CSS/common.css\">\n");
      out.write("\t<link rel=\"stylesheet\" href=\"CSS/login-formatting.css\">\n");
      out.write("\t<link rel=\"stylesheet\" href=\"CSS/tableFormatting.css\">\n");
      out.write("\t\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div id=header>\n");
      out.write("\n");
      out.write("\t\t<ul>\n");
      out.write("\t\t\t<li class=\"name\"><a>Quizzler</a></li>\n");
      out.write("\t\t\t<li><a href=\"HomepageLogin.html\">Logout</a></li>\n");
      out.write("\t\t\t<li><a href=\"ListQuizzes.jsp\">Quizzes</a></li>\n");
      out.write("\t\t\t<li><a href=\"/Quizlet/HomepageUser.jsp\">Profile</a></li>\n");
      out.write("\t\t\t<li><a href=\"HistorySummaryPage.jsp\">History</a></li>\n");
      out.write("\t\t</ul>\n");
      out.write("\t\t<div id=\"extra-large-inner-header\">\n");
      out.write("\n");
      out.write("\t\t\t<h1>");
      out.print(currentuser );
      out.write("'s Quiz History </h1>\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t");

			

 			if (request.getAttribute("error") != null) {
 				out.println(request.getAttribute("error"));
 			}
 			
			
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t");

			out.println("<p><strong>Your Past Performance:</strong> </p>");
			out.write("<table>");
			out.write("<tr>");
			out.write("<th>Quiz Name</th><th>Date Taken</th><th>Score</th><th>Time</th>");
			out.write("<tr>");
			
			try {
				ResultSet rs = stmt.executeQuery("SELECT * FROM quizzes");
				
				while(rs.next()) {
					String quizname = rs.getString(2);

					Blob boardblob = rs.getBlob(7);
					
					board = new ScoreBoard(boardblob);
					for (Score sc : board.getUsers()) {
						if (sc.user.equals(currentuser)){
							Date dt = new Date(sc.timetaken);
							out.println("<tr>");
							out.println("<td>"+ quizname+"</td><td>"+ dt.toString()+"</td><td>"+sc.score+"</td><td>"+sc.timescore+"</td>");
							out.println("</tr>");
						}
					}
					
				}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			

			out.write("</table>");
			out.write("</div>");
	
			
      out.write(" \n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<form action=\"HomepageUser.jsp\" method=\"post\">\n");
      out.write("\t\t\t\t  <input type=\"submit\" class=\"btn btn-primary\" value = \"Back\"/>\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\n");
      out.write("\t \t</div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
